enum GenedType {
  # Science Gened
  SC
  # Interdisciplinary Gened
  IN
  # Human Gened
  HU
  # Social Science Gened
  SO
}

interface Course {
  _id: ID!
  courseID: String!
  name: String!
  shortName: String!
  credit: Float!
  exam: [Date]

  sections(first: Int, after: ID): SectionPage
}

type NormalCourse implements Course, Node {
  _id: ID!
  courseID: String!
  name: String!
  shortName: String!
  credit: Float!
  exam: [Date]

  sections(first: Int, after: ID): SectionPage
}

type GenedCourse implements Course, Node {
  _id: ID!
  courseID: String!
  name: String!
  shortName: String!
  credit: Float!
  exam: [Date],
  type: String!,

  sections(first: Int, after: ID): SectionPage
  
  type: GenedType!
  genedSections(first: Int, after: ID): SectionPage
}

type ApprovedCourse implements Course, Node {
  _id: ID!
  courseID: String!
  name: String!
  shortName: String!
  credit: Float!
  exam: [Date]

  sections(first: Int, after: ID): SectionPage

  faculty: String!
  department: String!
  approvedSections(first: Int, after: ID): SectionPage
}