query CourseInActions($ids: [ID]) {
  courses(sectionIDs: $ids) {
    section {
      _id
      sectionNo
      timeIntervals {
        day
        start
        end
      }
      teachers {
        abbreviated
      }
    }
    course {
      _id
      courseID
      name
    }
  }
}