query CourseInActions($ids: [ID]) {
  courses(sectionIDs: $ids) {
    _id
    courseID
    name
    sections {
      edges {
        node {
          _id
          timeIntervals {
            day
            start
            end
          }
          teachers {
            abbreviated
          }
          building
          classroom
          type
        }
      }
    }
  }
}