query ($id: ID!) {
    me {
      coursetable(id: $id) {
        _id
        courses {
          section
          course {
            _id
            name
          }
          timeIntervals {
            day
            start
            end
          }
        }
      }
    }
  }