query ($first: Int, $after: ID) {
    me {
      coursetables(first: $first, after: $after) {
        edges {
          node {
            _id
            courses {
              timeIntervals {
                day
                start
                end
              },
              color
            }
          }
        }
        pageInfo {
          endCursor
        }
      }
    }
  }