type SectionEdges implements Edges {
  node: Section!
  cursor: ID!
}

type SectionPage implements Page {
  totalCount: Int!
  edges: [SectionEdges]
  pageInfo: PageInfo
}
# Section Type
enum SectionType {
  NORMAL
  GENED
  APPROVE
}
# Section
type Section implements Node {
  _id: ID!
  timeIntervals: [TimeInterval]!
  teachers: [Teacher]
  building: String
  classroom: String
  type: SectionType!
}