language: node_js
node_js:
- '6'
- '7'
before_install:
- yarn install
- yarn global add typescript@2.2.1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- yarn lint
- yarn test
services:
- mongodb 
cache:
  yarn: true