query Courses($search: String!) {
  courses(search: $search) {
    _id
    name
    sections {
      edges {
        node {
          _id
          timeIntervals {
            day
            start
            end
          }
          teachers {
            abbreviated
          }
          building
          classroom
          type
        }
      }
    }
  }
}
