query Courses($search: String!) {
  search(search: $search) {
    edges {
      node {
        ... on NormalCourse {
          _id
          courseID
          name
          sections {
            edges {
              node {
                _id
                timeIntervals {
                  day
                  start
                  end
                }
                teachers {
                  abbreviated
                }
                building
                classroom
                type
              }
            }
          }
        }
        
        ... on GenedCourse {
          _id
          courseID
          name
          sections {
            edges {
              node {
                _id
                timeIntervals {
                  day
                  start
                  end
                }
                teachers {
                  abbreviated
                }
                building
                classroom
                type
              }
            }
          }
        }
        
        ... on CourseGroup {
          _id
          name
          courses {
            _id
            courseID
            name
          }
          faculty
          department
          year
        }
      }
    }
  }
}
