# Root Query
type Query {
  helloworld: String

  me: User
  search(search: String!): SearchResultPage

  courses(sectionIDs: [ID]): [CourseTableSection]
  coursegroup(id: ID): CourseGroup

  intl(locale: String!): [IntlMessage]
}