query CourseGroup($id: ID) {
  coursegroup(id: $id) {
    name
    faculty
    department
    year
    courses {
      _id
      courseID
      name
      sections {
        edges {
          node {
            _id
            sectionNo
            timeIntervals {
              day
              start
              end
            }
            teachers {
              abbreviated
            }
            building
            classroom
            type
          }
        }
      }
    }
  }
}