export const PUSH_ADD_COURSE_ACTION = 'PUSH_ADD_COURSE_ACTION';
export const PUSH_REMOVE_COURSE_ACTION = 'PUSH_REMOVE_COURSE_ACTION';
export const PUSH_CHANGE_SECTION_ACTION = 'PUSH_CHANGE_SECTION_ACTION';
export const EXEC_ACTIONS = 'EXEC_ACTIONS';
export const CLEAR_ACTIONS = 'CLEAR_ACTIONS';
