type Account {
  id: String
  email: String
  facebookAccessCode: String
  googleAccessCode: String
}

# Edges for CourseTableQuery
type CourseTableEdges {
  node: CourseTable
  cursor: ID
}

# Course table relay-style pagination query
type CourseTablePage implements Page {
  totalCount: Int
  edges: [CourseTableEdges]
  pageInfo: PageInfo
}

# A user
type User {
  _id: String
  name: String
  avatar: String
  createAt: Date
  updateAt: Date
  account: Account

  coursetables(first: Int, after: ID): CourseTableQuery
  coursetable(id: ID!): CourseTable
}