type Account {
  id: String
  email: String
  facebookAccessCode: String
  googleAccessCode: String
}

# A user
type User {
  _id: String
  name: String
  avatar: String
  createAt: Date
  updateAt: Date
  coursetables(cursor: $cursor): [CourseTable]
}