query SuggestCourseGroup {
  me {
    _id
    suggestCourseGroup {
      _id
      name
      faculty
      department
      year
      courses {
        _id
        name
        courseID
      }
    }
  }
}